import styles from "./confidentiality.module.css";

export const Confidentiality = () => {
    
    return (
        <div className={styles.confidentiality}>
            <h1>Personal data processing policy</h1>
            <p>Approved by the Order of the General Director of Fabrika-kukhnya LLC No. 110/23 of 29.08.2023</p>
            <h2>1. General provisions</h2>
            <p>1.1 This Policy on personal data processing (hereinafter - “Policy”) is developed and applied by Fabrika-Kukhnya LLC (hereinafter also - “Operator”) in accordance with the Federal Law dated 27.07.2006 № 152-FZ “On Personal Data”, the Federal Law dated 13.03.2006 № 38-FZ “On Advertising”, and other regulations in the field of personal data protection in force in the territory of the Russian Federation.</p>
            <p>1.2 This Policy is part of the general policy regarding the processing of personal data of Fabrika-kukhnya LLC.</p>
            <p>1.3 The Policy defines the Operator's behavior with regard to the processing of personal data accepted for processing, the procedure and conditions of personal data processing of individuals who have transferred their personal data for processing to the Operator (hereinafter also referred to as “Personal Data Subject”, “Subject”) with and without the use of automation, establishes procedures aimed at preventing violations of the legislation of the Russian Federation, eliminating the consequences of such violations related to the processing of personal data</p>
            <p>1.4 The Policy is developed in order to ensure protection of the rights and freedoms of Personal Data Subjects during processing of their personal data, as well as to establish the responsibility of the Operator's officials who have access to personal data of Personal Data Subjects for failure to comply with the requirements and regulations governing the processing of personal data.</p>
            <h2>2. Receipt, use and disclosure of personal data</h2>
            <p>2.1 The Operator receives and starts processing the Subject's personal data from the moment of receiving his/her consent. Consent to the processing of personal data may be given by the Data Subject in any form that allows confirming the fact of obtaining consent, unless otherwise provided for by federal law: in writing, orally or in any other form provided for by applicable law, including through the performance by the Data Subject of exclusive actions (acceptance of the offer posted on the Website and in the Appendix). In the absence of the Personal Data Subject's consent to the processing of his/her personal data, such processing is not carried out.</p>
            <p>2.2 The consent shall be deemed to have been duly obtained and shall be valid until the Personal Data Subject sends a corresponding application for termination of personal data processing to the location of the Operator.</p>
            <p>2.3 The Personal Data Subject may withdraw his/her consent to the processing of personal data at any time, provided that such procedure does not violate the requirements of the legislation of the Russian Federation. To withdraw consent to the processing of personal data, the Personal Data Subject should send a written notice to the following postal address: 195197, St. Petersburg, Kondratievsky Ave. 15, bldg. 5, p. 1, room 3H, office 105. 1, room 3H, office 105. If the Personal Data Subject revokes his/her consent to the processing of his/her personal data, the Operator shall cease processing or ensure the cessation of such processing (if the processing is performed by another person acting on behalf of the Operator) and, if the preservation of personal data is no longer required for the purposes of their processing, destroy the personal data or ensure their destruction (if the processing of personal data is performed by another person acting on behalf of the Operator).</p>
            <p>2.4 If a reasonable request is received from the data subject that the data is being used illegally, the term for destroying the Personal Data shall be 7 business days from the date of receipt of the request, and if a violation of the principles of interaction with Personal Data is independently detected, the term shall be 10 business days from the date of detection. If the purpose of using the Personal Data has been achieved, the term shall be 30 days from the date of achievement of the purpose. Unless otherwise specified in the agreement with the data controller and if the purpose of using the personal data has been achieved, if the consent is withdrawn, the period of personal data destruction will be 30 days from the date of its receipt. If the data subject's request to cease processing is received, the elimination period is 10 working days. It may be extended, but for no more than 5 working days and upon sending a notice stating the reasons for the extension.</p>
            <h2>3. Rules and procedure for processing personal data</h2>
            <p>3.1 In order to achieve the goals of this Policy, only those employees of the Operator who are assigned such duty in accordance with their official (labor) responsibilities are allowed to process personal data. The Operator requires from its employees to observe confidentiality and security of personal data during their processing.</p>
            <p>3.2 In accordance with this Policy, the Operator may process personal data independently, as well as with the involvement of third parties, which are engaged by the Operator and carry out processing for the purposes specified in this Policy.</p>
            <p>3.3 In case of entrusting the processing of personal data to a third party, the amount of personal data transferred to the third party for processing and the number of processing methods used by the third party shall be minimally necessary for the third party to fulfill its obligations to the Operator. With regard to the processing of personal data by a third party, the obligation of such third party to maintain the confidentiality of personal data and ensure the security of personal data during their processing shall be established.</p>
            <p>3.4 In the process of providing services, in the course of internal business activities, the Operator uses both automated, using computer facilities, and non-automated, using paper-based document flow, processing of personal data. The Operator does not make decisions that have legal consequences for the Personal Data Subject or otherwise affect his/her rights and legitimate interests on the basis of exclusively automated processing of personal data. The Operator stores personal information of Personal Data Subjects in accordance with the internal regulations.</p>
            <p>3.5 The personal information of the Personal Data Subject shall be kept confidential, except for the cases when the Subject voluntarily provides information about himself/herself for public access to an unlimited number of persons. In this case, the Data Subject agrees that a certain part of his/her personal information becomes publicly available.</p>
        </div>
    )
}